### PR TITLE
feat: make fetch library import customizable

### PR DESCRIPTION
**Pull request by lucat1**
Implements the `-fetch-library` flag for the `rpc-ts-client` generator, allowing to change the import module or remove it entirely when providing `none` as the value.

I am happy to add documentation and tests if needed(just need to know where).

### CODE REVIEW

**Comment by tj** [comment]
Sweet thanks! It might be a bit awkward, but it would be awesome if we can support the different JS envs in the same build. Ideally we just build the one for JS and the bundle works in the browser, Node, and Deno

**Comment by lucat1** [comment]
I see what you're after. To achieve that we'd have to output something like this:
```javascript
let fetch = typeof window !== 'undefined' ? window.fetch : null
if(!fetch) {
  fetch = require('<lib>')
}
```
This approach will also allow loading ponyfills like [unfetch](https://github.com/developit/unfetch#usage-as-a-ponyfill) via [isomorphic](https://github.com/developit/unfetch/tree/master/packages/isomorphic-unfetch) libraries.
I still think the `-fetch-library` flag should be kept to allow importing whatever library people desire.

**Comment by tj** [comment]
Ideally the do the "right thing" by default, and people can fork or write their own generators if they want something custom. I guess if bundling all the JS stuff as a single package doesn't work we could always split it later, but in that case I think they should be separate commands — `rpc-deno-client` for example — using the same package internally

**Comment by tj** [comment]
LGTM though! Thanks man

**Comment by lucat1** [comment]
The current implementation should work on deno, web and node AFAIK. No need to split packages yet

**Comment by tj** [comment]
Perfect! I'll give it a try with Deno later today

**Pull request merged**
